on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: ${{github.workspace}}/cross-build.sh

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
